steps:
  - label: ":ballot_box_with_ballot:"
    command: ./src/generate-and-store-number.sh
    key: generate-numbers

  # - wait

  - label: ":desktop_computer:"
    command: ./src/fetch-and-display-number.sh
    depends_on: 
    - generate-numbers
